name: Run tests

on: [ push, pull_request ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                php: [ 7.4, 8.0, 8.1 ]
                laravel: [ 6.*, 7.*, 8.*, 9.* ]
                dependency-version: [ prefer-stable ]
                include:
                    -   testbench: 7.*
                        laravel: 9.*
                    -   testbench: 6.*
                        laravel: 8.*
                    -   testbench: 5.*
                        laravel: 7.*
                    -   testbench: 4.*
                        laravel: 6.*
                exclude:
                    - php: 8.1
                      laravel: 6.*
                    - php: 8.1
                      laravel: 7.*
                    - php: 7.4
                      laravel: 9.*

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: pcov

            -   name: Install dependencies
                run: |
                    composer require "illuminate/broadcasting:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction
                    composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
